name: darty_commons
description: Darty Commons is a Package that provides a punch of useful extension methods for every application functionalities (Inspired by Anko Commons in Kotlin)
version: 0.1.2
homepage: https://github.com/AhmedBeheiri/dart_commons
documentation: https://github.com/AhmedBeheiri/dart_commons

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  flutter_phone_direct_caller: ^1.0.1
  url_launcher: ^5.5.0
  share: '>=0.6.4+3 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  module:
    androidX: true
    androidPackage: com.ahmed_beheiri.dart_common
    iosBundleIdentifier: com.ahmedbeheiri.dartCommon
